### ISSUE TITLE
FG Next/Nightly Crash when adding centre tanks.

### ISSUE THREAD

**Issue by Megaf** [5H1N0B11/flightgear-mirage2000#227]
On FlightGear Next, the Mirage and F-16 will crash, with a `Segmentation fault` almost every time, when using `Fuel and Payload` -> Add centre tanks and/or wing tanks.

`Program terminated with signal SIGSEGV, Segmentation fault.`

Crash happens in both OSG 3.6 and 3.7.

```
FlightGear version: 2020.4.0
SimGear version: 2020.4.0
OSG version: 3.7.0
PLIB version: 185
```

**Coredump**
```
#0  0x0000000000822feb in FGPUIDialog::applyValues(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x0000000000e40d66 in do_dialog_apply(SGPropertyNode const*, SGPropertyNode*) ()
#2  0x00000000011e19d1 in SGBinding::innerFire() const ()
#3  0x0000000000823a59 in action_callback(puObject*) ()
#4  0x000000000155e5b9 in puOneShot::doHit(int, int, int, int) ()
#5  0x000000000155dd4c in puObject::checkHit(int, int, int, int) ()
#6  0x000000000155ec17 in puPopupMenu::checkHit(int, int, int, int) ()
#7  0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#8  0x0000000000823140 in non-virtual thunk to fgComboBox::checkHit(int, int, int, int) ()
#9  0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#10 0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#11 0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#12 0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#13 0x0000000000826985 in fgPopup::checkHit(int, int, int, int) ()
#14 0x000000000155a86f in puGroup::checkHit(int, int, int, int) ()
#15 0x0000000001557e13 in puMouse(int, int, int, int) ()
#16 0x0000000000e119f8 in PUIEventHandler::handle(osgGA::GUIEventAdapter const&, osgGA::GUIActionAdapter&, osg::Object*, osg::NodeVisitor*) ()
#17 0x00007fafccb9b177 in osgGA::GUIEventHandler::handle(osgGA::Event*, osg::Object*, osg::NodeVisitor*) () at /home/reglnx/root/lib/libosgGA.so.202
#18 0x00007fafccef73b7 in osgViewer::CompositeViewer::eventTraversal() () at /home/reglnx/root/lib/libosgViewer.so.202
#19 0x00007fafccf48d9c in osgViewer::ViewerBase::frame(double) [clone .part.0] () at /home/reglnx/root/lib/libosgViewer.so.202
#20 0x0000000000db3358 in fgOSMainLoop() ()
#21 0x0000000000e69364 in fgMainInit(int, char**) ()
#22 0x000000000060b85c in main ()
```

**Comment by vanosten** [comment]
Does not happen here. Also: given the major changes in NEXT/2024.2 it should be revalidated and reopened if needed.
